### ISSUE TITLE
这是什么类库啊

### ISSUE THREAD

**Issue by cckmit** [aliyun/tea-java#147]
这是什么类库啊

**Comment by Wu-Jianqiang** [comment]
同问，这是什么类库啊？

**Comment by yndu13** [comment]
这个是阿里云 OpenAPI 升级版 SDK 的核心库，感兴趣的可以了解下开发者门户：https://next.api.aliyun.com/home，门户上会列出云产品 SDK 的各个版本，包括升级版 SDK 和原版 SDK。

**Comment by Wu-Jianqiang** [comment]
去门户网站看了，还是不知道为什么叫“tea”，实现目标和原理是什么？
