### ISSUE TITLE
请check：org.jacoco:org.jacoco.agent被传递依赖

### ISSUE THREAD

**Issue by btpka3** [aliyun/tea-java#169]
根 [pom.xml](https://github.com/aliyun/tea-java/blob/0f548097573b790a04ef63e81664525b2c40e507/pom.xml#L112) 中对依赖 org.jacoco:org.jacoco.agent 的 scope 设置的是  runtime， 会让所有使用方都获得该传递依赖的。 但jacoco 应该只是单测时计算覆盖率使用的吧，请 double check下吧。如果只是单测使用，完全可以删除该依赖的， jacoco-maven-plugin 也仍然会work的。

**Comment by JacksonTian** [comment]
fixed via a50c64842f65ce678861a8df76ce649db6e2667a
